// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: grpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigFormat int32

const (
	ConfigFormat_YAML ConfigFormat = 0
	ConfigFormat_JSON ConfigFormat = 1
)

// Enum value maps for ConfigFormat.
var (
	ConfigFormat_name = map[int32]string{
		0: "YAML",
		1: "JSON",
	}
	ConfigFormat_value = map[string]int32{
		"YAML": 0,
		"JSON": 1,
	}
)

func (x ConfigFormat) Enum() *ConfigFormat {
	p := new(ConfigFormat)
	*p = x
	return p
}

func (x ConfigFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_enumTypes[0].Descriptor()
}

func (ConfigFormat) Type() protoreflect.EnumType {
	return &file_grpc_proto_enumTypes[0]
}

func (x ConfigFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigFormat.Descriptor instead.
func (ConfigFormat) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{0}
}

type InspectConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        ConfigFormat           `protobuf:"varint,1,opt,name=format,proto3,enum=proto.ConfigFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectConfigRequest) Reset() {
	*x = InspectConfigRequest{}
	mi := &file_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectConfigRequest) ProtoMessage() {}

func (x *InspectConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectConfigRequest.ProtoReflect.Descriptor instead.
func (*InspectConfigRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *InspectConfigRequest) GetFormat() ConfigFormat {
	if x != nil {
		return x.Format
	}
	return ConfigFormat_YAML
}

type InspectStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectStatusRequest) Reset() {
	*x = InspectStatusRequest{}
	mi := &file_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectStatusRequest) ProtoMessage() {}

func (x *InspectStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectStatusRequest.ProtoReflect.Descriptor instead.
func (*InspectStatusRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{1}
}

type InspectVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectVersionRequest) Reset() {
	*x = InspectVersionRequest{}
	mi := &file_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectVersionRequest) ProtoMessage() {}

func (x *InspectVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectVersionRequest.ProtoReflect.Descriptor instead.
func (*InspectVersionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{2}
}

type InspectLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"zigzag32,1,opt,name=level,proto3" json:"level,omitempty"` // respect to definition in slog package
	Plain         bool                   `protobuf:"varint,2,opt,name=plain,proto3" json:"plain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectLogRequest) Reset() {
	*x = InspectLogRequest{}
	mi := &file_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectLogRequest) ProtoMessage() {}

func (x *InspectLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectLogRequest.ProtoReflect.Descriptor instead.
func (*InspectLogRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *InspectLogRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *InspectLogRequest) GetPlain() bool {
	if x != nil {
		return x.Plain
	}
	return false
}

type StringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             string                 `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringResponse) Reset() {
	*x = StringResponse{}
	mi := &file_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringResponse) ProtoMessage() {}

func (x *StringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringResponse.ProtoReflect.Descriptor instead.
func (*StringResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *StringResponse) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

var File_grpc_proto protoreflect.FileDescriptor

const file_grpc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"grpc.proto\x12\x05proto\"C\n" +
	"\x14InspectConfigRequest\x12+\n" +
	"\x06format\x18\x01 \x01(\x0e2\x13.proto.ConfigFormatR\x06format\"\x16\n" +
	"\x14InspectStatusRequest\"\x17\n" +
	"\x15InspectVersionRequest\"?\n" +
	"\x11InspectLogRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x11R\x05level\x12\x14\n" +
	"\x05plain\x18\x02 \x01(\bR\x05plain\"\x1e\n" +
	"\x0eStringResponse\x12\f\n" +
	"\x01s\x18\x01 \x01(\tR\x01s*\"\n" +
	"\fConfigFormat\x12\b\n" +
	"\x04YAML\x10\x00\x12\b\n" +
	"\x04JSON\x10\x012\xa0\x02\n" +
	"\x04GRPC\x12E\n" +
	"\rInspectConfig\x12\x1b.proto.InspectConfigRequest\x1a\x15.proto.StringResponse\"\x00\x12E\n" +
	"\rInspectStatus\x12\x1b.proto.InspectStatusRequest\x1a\x15.proto.StringResponse\"\x00\x12G\n" +
	"\x0eInspectVersion\x12\x1c.proto.InspectVersionRequest\x1a\x15.proto.StringResponse\"\x00\x12A\n" +
	"\n" +
	"InspectLog\x12\x18.proto.InspectLogRequest\x1a\x15.proto.StringResponse\"\x000\x01B\x11Z\x0ffippf/cli/protob\x06proto3"

var (
	file_grpc_proto_rawDescOnce sync.Once
	file_grpc_proto_rawDescData []byte
)

func file_grpc_proto_rawDescGZIP() []byte {
	file_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_rawDesc), len(file_grpc_proto_rawDesc)))
	})
	return file_grpc_proto_rawDescData
}

var file_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_proto_goTypes = []any{
	(ConfigFormat)(0),             // 0: proto.ConfigFormat
	(*InspectConfigRequest)(nil),  // 1: proto.InspectConfigRequest
	(*InspectStatusRequest)(nil),  // 2: proto.InspectStatusRequest
	(*InspectVersionRequest)(nil), // 3: proto.InspectVersionRequest
	(*InspectLogRequest)(nil),     // 4: proto.InspectLogRequest
	(*StringResponse)(nil),        // 5: proto.StringResponse
}
var file_grpc_proto_depIdxs = []int32{
	0, // 0: proto.InspectConfigRequest.format:type_name -> proto.ConfigFormat
	1, // 1: proto.GRPC.InspectConfig:input_type -> proto.InspectConfigRequest
	2, // 2: proto.GRPC.InspectStatus:input_type -> proto.InspectStatusRequest
	3, // 3: proto.GRPC.InspectVersion:input_type -> proto.InspectVersionRequest
	4, // 4: proto.GRPC.InspectLog:input_type -> proto.InspectLogRequest
	5, // 5: proto.GRPC.InspectConfig:output_type -> proto.StringResponse
	5, // 6: proto.GRPC.InspectStatus:output_type -> proto.StringResponse
	5, // 7: proto.GRPC.InspectVersion:output_type -> proto.StringResponse
	5, // 8: proto.GRPC.InspectLog:output_type -> proto.StringResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_init() }
func file_grpc_proto_init() {
	if File_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_rawDesc), len(file_grpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_proto_depIdxs,
		EnumInfos:         file_grpc_proto_enumTypes,
		MessageInfos:      file_grpc_proto_msgTypes,
	}.Build()
	File_grpc_proto = out.File
	file_grpc_proto_goTypes = nil
	file_grpc_proto_depIdxs = nil
}
